version: '3.8'

services:
  backend:
    build: .
    container_name: compafest_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=development
      - PROJECT_NAME=Warehouse AI API
      - DATA_CSV_PATH=app/data/indonesia_e-commerce_sales_and_shipping_2023–2025/all_months_clean.csv
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
